[package]
name = "comet"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "agent-deski"
path = "src/main.rs"

[dependencies]
comet-engine.workspace = true
comet-ui.workspace = true
comet-update.workspace = true
tokio.workspace = true
clap.workspace = true
mimalloc.workspace = true
anyhow.workspace = true
dotenvy.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
embed-resource = "2.5"
