/**
 * Grok Build BYOK: materialize `~/.grok/config.toml` from the app's selected
 * provider so `grok agent stdio` can call Anthropic-compatible gateways.
 *
 * api_backend is always "messages" (Anthropic Messages API).
 * See: https://docs.x.ai/build/settings
 * Ref: https://github.com/shivaylamba/grok-build-nebius
 */
import { mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import type {
  AgentInfo,
  ClaudeModelAlias,
  ProviderConfig,
} from "../shared/rpc";
import {
  normalizeModelAlias,
  resolveActiveProvider,
  resolveProviderModel,
} from "./providers";
import type { AppSettings } from "../shared/rpc";

/** Env var name written into config.toml and set on the grok process. */
export const GROK_PROVIDER_API_KEY_ENV = "AGENT_DESK_GROK_API_KEY";

/** Stable catalog id used as [models].default and [model."…"]. */
export const GROK_PROVIDER_MODEL_ID = "agent-desk";

export function grokHomeDir(env: NodeJS.ProcessEnv = process.env): string {
  const fromEnv = env.GROK_HOME?.trim();
  if (fromEnv) return fromEnv;
  return join(homedir(), ".grok");
}

export function grokConfigPath(env: NodeJS.ProcessEnv = process.env): string {
  return join(grokHomeDir(env), "config.toml");
}

export function isGrokStyleAgent(
  agent: Pick<AgentInfo, "id" | "command" | "name" | "args">,
): boolean {
  const id = agent.id.toLowerCase();
  if (id === "grok-build" || id === "grok" || id.startsWith("grok-")) {
    return true;
  }
  const cmd = agent.command.replace(/\\/g, "/").split("/").pop() ?? agent.command;
  const base = cmd.replace(/\.exe$/i, "").toLowerCase();
  if (base !== "grok" && base !== "xai-grok-pager") return false;
  const args = agent.args ?? [];
  if (args.length === 0) return true;
  return args[0] === "agent" && (args[1] === "stdio" || args.length === 1);
}

function tomlString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/**
 * Grok `base_url` is an OpenAI/Anthropic-style root ending in `/v1`
 * (client appends `/messages` when api_backend = "messages").
 * Append `/v1` only when the provider URL does not already end with it.
 */
export function normalizeGrokBaseUrl(raw: string): string {
  const trimmed = raw.trim().replace(/\/+$/, "");
  if (!trimmed) return "";
  if (/\/v1$/i.test(trimmed)) return trimmed;
  return `${trimmed}/v1`;
}

/**
 * Build ~/.grok/config.toml contents for the selected provider.
 * Pins default + aux models to the same upstream id (non-xAI endpoints 404 on grok-build).
 */
export function buildGrokConfigToml(
  provider: ProviderConfig,
  modelAlias: ClaudeModelAlias,
): string {
  const upstream = resolveProviderModel(provider, modelAlias);
  const baseUrl = normalizeGrokBaseUrl(provider.baseUrl);
  const name = provider.name.trim() || "Provider";
  const isXai =
    /(?:^|\.)x\.ai(?:\/|$)/i.test(baseUrl) ||
    /api\.x\.ai/i.test(baseUrl);

  const lines: string[] = [
    "# Generated by Agent Desk — do not edit by hand while using app providers.",
    "# Recreated when a Grok session starts or a prompt is sent with a selected provider.",
    "",
  ];

  // Built-in web search only works on xAI /responses tooling.
  if (!isXai) {
    lines.push("disable_web_search = true", "");
  }

  lines.push(
    "[cli]",
    "auto_update = false",
    "",
    "[models]",
    `default = ${tomlString(GROK_PROVIDER_MODEL_ID)}`,
    // Aux models send this string on the wire; must be a real upstream id.
    `session_summary = ${tomlString(upstream)}`,
    `image_description = ${tomlString(upstream)}`,
    "",
    // Dotted ids must be quoted or TOML nests the table.
    `[model.${tomlString(GROK_PROVIDER_MODEL_ID)}]`,
    `model = ${tomlString(upstream)}`,
    `base_url = ${tomlString(baseUrl)}`,
    `name = ${tomlString(name)}`,
    `description = ${tomlString(`Agent Desk provider (${provider.id})`)}`,
    `env_key = ${tomlString(GROK_PROVIDER_API_KEY_ENV)}`,
    'api_backend = "messages"',
    "",
  );

  if (!isXai) {
    lines.push(
      "[features]",
      "telemetry = false",
      "feedback = false",
      "managed_config = false",
      "backend_tools = false",
      "web_fetch = false",
      "",
    );
  }

  return lines.join("\n");
}

/**
 * Env overrides for the grok subprocess (API key for env_key in config.toml).
 * Returns null when there is nothing to inject.
 */
export function buildGrokProviderEnv(
  provider: ProviderConfig | null,
): Record<string, string> | null {
  if (!provider) return null;
  const key = provider.apiKey.trim();
  if (!key) return null;
  return { [GROK_PROVIDER_API_KEY_ENV]: key };
}

export type EnsureGrokConfigResult =
  | { ok: true; path: string; wrote: true }
  | { ok: true; path: string; wrote: false; reason: "no-provider" | "no-base-url" | "no-model" }
  | { ok: false; error: string };

/**
 * Write config.toml for the active provider when Grok is about to run.
 * Skips write if no usable provider/model is configured.
 */
export async function ensureGrokConfigForProvider(
  settings: Pick<
    AppSettings,
    "providers" | "activeProviderId" | "activeModelAlias"
  >,
  options?: {
    env?: NodeJS.ProcessEnv;
    writeFile?: (path: string, contents: string) => Promise<void>;
  },
): Promise<EnsureGrokConfigResult> {
  const env = options?.env ?? process.env;
  const path = grokConfigPath(env);
  const provider = resolveActiveProvider(settings);
  if (!provider) {
    return { ok: true, path, wrote: false, reason: "no-provider" };
  }
  if (!provider.baseUrl.trim()) {
    return { ok: true, path, wrote: false, reason: "no-base-url" };
  }

  const alias = normalizeModelAlias(settings.activeModelAlias, "sonnet");
  const model = resolveProviderModel(provider, alias).trim();
  if (!model) {
    return { ok: true, path, wrote: false, reason: "no-model" };
  }

  const contents = buildGrokConfigToml(provider, alias);
  const write =
    options?.writeFile ??
    (async (p: string, data: string) => {
      mkdirSync(grokHomeDir(env), { recursive: true });
      await Bun.write(p, data);
    });

  try {
    await write(path, contents);
    return { ok: true, path, wrote: true };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { ok: false, error: message };
  }
}
